<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">

    <!-- Define xacro properties for positions and dimensions -->
    <xacro:property name="body_height" value="0.25"/>
    <xacro:property name="body_length" value="0.6"/>
    <xacro:property name="body_width" value="0.4"/>

    <xacro:property name="wheel_radius" value="0.12"/>
    <xacro:property name="wheel_length" value="0.05"/>
    <xacro:property name="wheel_distance_from_center" value="${body_width / 2 + wheel_length / 2}"/>

    <xacro:property name="camera_height" value="0.25"/>

    <xacro:property name="base_link_z" value="${wheel_radius + body_height}"/>

    <xacro:include filename="example_include.xacro"/>
    <xacro:include filename="example_gazebo.xacro"/>


    <!-- Base Link -->
    <link name="base_link">
    </link>

      <link name="world">
        <origin xyz="0 0 0"/>
    </link>


    <joint name="base_link_joint" type="fixed">
        <parent link="world"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${base_link_z}"/>
    </joint>

    <!-- Chasis Link -->
    <link name="chasis">
        <visual>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <material name="bodyTexture">
                <color rgba="1 1 1 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="10.0"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
        </inertial>
    </link>

    <joint name="chasis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chasis"/>
        <origin xyz="0 0 -${body_height / 2}"/>
    </joint>

    <!-- Left Wheel -->
    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1.0"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
        </inertial>
    </link>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="chasis"/>
        <child link="left_wheel"/>
        <origin xyz="${body_length / 2} ${wheel_distance_from_center} -${wheel_radius}" rpy="1.5708 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <!-- Right Wheel -->
    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1.0"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
        </inertial>
    </link>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="chasis"/>
        <child link="right_wheel"/>
        <origin xyz="${body_length / 2} -${wheel_distance_from_center} -${wheel_radius}" rpy="1.5708 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <!-- Caster Wheel -->
    <link name="caster_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1.0"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
        </inertial>
    </link>

    <joint name="caster_wheel_joint" type="continuous">
        <parent link="chasis"/>
        <child link="caster_wheel"/>
        <origin xyz="-${body_length / 2} 0 -${wheel_radius}" rpy="1.5708 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <!-- Camera Link -->
    <link name="camera_link">
        <visual>
            <geometry>
                <box size="0.1 0.05 0.05"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.1 0.05 0.05"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.5"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
        </inertial>
    </link>

    <joint name="camera_joint" type="fixed">
        <parent link="chasis"/>
        <child link="camera_link"/>
        <origin xyz="0 0 ${body_height / 2}"/>
    </joint>


</robot>
